### ISSUE TITLE
Relocating and catalogging channel runs

### ISSUE THREAD

**Issue by charlesbluca** [pangeo-data/pangeo-datastore#103]
Our current situation with regards to channel runs is reflected in [channel.yaml](https://github.com/pangeo-data/pangeo-datastore/blob/master/intake-catalogs/ocean/channel.yaml); because both of these entries are MITgcm-based, they are contained in a bucket corresponding to that project - `gs://pangeo-ldeo-mitgcm`. It would be nice to move the additional channel runs left in `gs://pangeo-data` to their own dedicated bucket, and add them to the preexisting channel catalog.

@dhruvbalwada, do you have any preferences for the name of the bucket we move this data to, or the names of the datasets as they appear in the catalog?

**Comment by rabernat** [comment]
I would say let's just use `pangeo-ldeo-mitgcm`. Thanks for looking into this @charlesbluca!

**Comment by charlesbluca** [comment]
Relocated the data to `gs://pangeo-ldeo-mitgcm` and opened up a PR to add the datasets to the catalog at #104 - once we have everything sorted out and merged we can remove the `gs://pangeo-data` copies of the data.

**Comment by charlesbluca** [comment]
Merged #104; now we just need to verify that the new data is accessible then we can remove the old copies.

**Comment by charlesbluca** [comment]
Checked the catalog site and my local machine - the data is accessible!

I went ahead and deleted the old copies of the data in `gs://pangeo-data`; thanks to everyone for the help!
