### ISSUE TITLE
Adding WeatherBench dataset

### ISSUE THREAD

**Issue by stepp1** [pangeo-data/pangeo-datastore#110]
Hi! 

I'm coming from an ML/Engineering background and for some time now I've been working with satellite and oceanographic data using xarray. Lately, my team and I are planning on tackling some weather/atmospheric data.

Wanted to ask if there are any plans on doing making the dataset possible. If there aren't, would be glad to contribute if needed. I checked the catalog and there seems to be some ERA5 data available but I think that the resolution is different, weatherbench's one seems to be regridded for ML/Deep Learning use.

Many thanks

**Comment by charlesbluca** [comment]
Is this dataset available publicly? Typically, the process of getting data added to the catalogs involves:

- Converting data to a cloud-optimized format (typically Zarr) if possible
- Moving this data to a publicly available means of cloud storage (usually a bucket associated with Pangeo's Google Cloud project)
- Making a pull request to add the data to an appropriate catalog in [intake-catalogs](https://github.com/pangeo-data/pangeo-datastore/tree/master/intake-catalogs), or adding a catalog if necessary

We also host [weekly meetings](https://pangeo.io/meeting-notes.html) via Zoom where we could bring this issue more visibility.

**Comment by stepp1** [comment]
Hi! Thanks for such a complete answer.

So, did a little search and came up with the following:

1. [WeatherBench's dataset](https://mediatum.ub.tum.de/1524895) is under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) which states the following:  _Free to Share: copy and redistribute the material in any medium or format_  but _No additional restrictions: You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits._ 
Not an expert on licensing but the "requester pays" logic might be a problem here.

2. The dataset has its [official repo](https://github.com/pangeo-data/WeatherBench) under the Pangeo project. This suggest that @raspstephan (one of the paper authors) is already 
working with the project. There might be a way here to fix issue 1. (if its even an issue). 

Personally, I might be able to do the conversion part on my uni's machines but this might take _some_ time.

**Comment by raspstephan** [comment]
Hi,
thanks for the interest in the dataset. Currently the dataset is available for download from [this server](https://mediatum.ub.tum.de/1524895) in netCDF format, so not on the cloud. I would be happy to support any efforts to put the data on the cloud. In terms of the license, I am not sure the license on the mediaTUM website matters, since it is just regridded ERA5 data and all the preprocessing scripts are available on the Github, so theoretically you could just create the data yourself. 

Let me know how I can be of help.

**Comment by rabernat** [comment]
> I would be happy to support any efforts to put the data on the cloud.

Hi @raspstephan - we are still happy to collaborate on this whenever you're ready!

The steps would be:
- convert to Zarr on your local machine (see [guide](http://pangeo.io/data.html#guide-to-preparing-cloud-optimized-data))
- upload to Google Cloud / AWS
- add to this catalog
