### ISSUE TITLE
Add CCMP winds to Pangeo

### ISSUE THREAD

**Issue by cgentemann** [pangeo-data/pangeo-datastore#112]
Hi.  @willirath and I both seem to use CCMP winds & have both put into Zarr.  
I think they would be helpful to have on Pangeo.  
The dataset goes from 7/1987 - 7/2020 and is 273 GB.  It is 25km x 25 km x 6 hourly data.
Zarr store chunks are 2000(time)x157(lat)x180(lon)  which are ~150MB files.
A nice description of the dataset is here: https://climatedataguide.ucar.edu/climate-data/ccmp-cross-calibrated-multi-platform-wind-vector-analysis?qt-climatedatasetmaintabs=1#qt-climatedatasetmaintabs

**Comment by rabernat** [comment]
👍  Great! We are happy to support this.

Eventually, pangeo-forge will be able to automate this ingestion. For now, it's still a manual process.

@charlesbluca - can you please set up a new bucket for this and work with @cgentemann to get the data uploaded and catalogged?

**Comment by charlesbluca** [comment]
Sure! @cgentemann, how does `gs://pangeo-ncar-ccmp` sound for a bucket name? From there, I can give you any additional privileges needed to upload the data there.

**Comment by cgentemann** [comment]
CCMP sponsored by MEASURES NASA program, how about gs://pangeo-nasa-ccmp  ?

**Comment by charlesbluca** [comment]
That works! I just created the bucket and can give you permissions - do you have an account associated with Pangeo's Google Cloud project?

**Comment by cgentemann** [comment]
great, thanks! moving conversation to gitter.

**Comment by cgentemann** [comment]
CCMP added to pangeo data store & master intake cat updated.
tutorial: https://github.com/cgentemann/cloud_science/blob/master/tutorials/Access_CCMP_pangeo.ipynb
