### ISSUE TITLE
Accessing Pangeo data on AWS storage

### ISSUE THREAD

**Issue by charlesbluca** [pangeo-data/pangeo-datastore#120]
I am trying to consolidate the metadata of `hydro.nldas_hru_forcing` and `hydro.usgs_streamflow_observations` as part of #119, but both reside in S3 and I do not have access to Pangeo's AWS project.

@scottyhq, are you able to give access to the project? If I know the steps to getting set up on AWS I can also document them in this repo's README and elsewhere.

**Comment by scottyhq** [comment]
Hi @charlesbluca If you need access to aws-uswest2.pangeo.io, you just need to fill out the form here https://pangeo.io/cloud.html#sign-up

If you need an IAM account with credentials on AWS that could probably be arranged, but I'm not sure we want to support these datasets in the long term, so we should consider moving them to some other storage system or different account. 

@jhamman or @rsignell-usgs might have ideas about where these USGS datasets should ultimately reside

**Comment by charlesbluca** [comment]
That's good to know! I'll fill out the form, and hopefully we can work out a different location - if we are comfortable with cross platform access, maybe these could be put in the CMIP6 buckets on Google Cloud and S3, in a similar fashion to our GFDL CM 2.6 products.
