### ISSUE TITLE
Error accessing Pangeo data catalogs

### ISSUE THREAD

**Issue by jdldeauna** [pangeo-data/pangeo-datastore#124]
Good day! I've been trying to [use the catalogs](https://github.com/jdldeauna/GitHub-Issues/blob/master/Access%20Pangeo%20catalogs.ipynb) outlined [here](https://catalog.pangeo.io/browse/master/), but have been encountering errors for each dataset. For example, when using the ocean catalog:

`cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean.yaml")`
`list(cat)`

This error appears: 
```
ValidationError: Catalog 'https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean.yaml' has validation errors:

("missing required key 'driver'", {'description': 'Estimating the Circulation and Climate of the Ocean (ECCO) State Estimate Ve'}) 
```

Additionally, I was able to open the [hydro catalog list](https://catalog.pangeo.io/browse/master/hydro/), but when trying to access a specific dataset:

`ds  = cat["cgiar_pet"].to_dask()`

This error appears:

`ValueError: Bad Request: https://www.googleapis.com/storage/v1/b/pangeo-cgiar-pet/o/.zarray
User project specified in the request is invalid.`

I'm unsure how to proceed. I'm using an OS X Catalina, and have installed the following plugins along with intake: intake-esm, intake-geopandas, intake-nested-yaml-catalog, intake-stac, and intake-xarray.

**Comment by rabernat** [comment]
Hi @jdldeauna and thanks for the comment. I'm a bit confused. 

I tried all your code on [https://us-central1-b.gcp.pangeo.io/](https://pangeo.io/cloud.html) and it all worked for me. This suggests that it is a package version and / or credentials issue.


This worked:

```python
from intake import open_catalog
cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean.yaml")
list(cat)
```

Can you report your intake version?
```python
import intake
print(intake.__version__ ) # -> 0.6.0 for me
````

I also tried
```python
from intake import open_catalog
cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/hydro.yaml")
ds = cat["cgiar_pet"].to_dask()
```

and it worked. Your error seems related to the [requester-pays](https://cloud.google.com/storage/docs/requester-pays) nature of these buckets. @martindurant might have some ideas about how to overcome it.

**Comment by martindurant** [comment]
Yes, you need to have a valid AWS login defined, either using environment variables (e.g., GCSFS_DEFAULT_PROJECT), a gsutil token file or default login (e.g., made by the login command), or [fsspec config](https://filesystem-spec.readthedocs.io/en/latest/features.html#configuration) to point to a valid token. The error message could be better, if indeed that is the problem.

**Comment by rabernat** [comment]
> Yes, you need to have a valid AWS login defined

You mean GCP login?

**Comment by martindurant** [comment]
Right yes - sorry

**Comment by martindurant** [comment]
Seems like its a real bug. https://github.com/intake/filesystem_spec/pull/599
This worked before because the file was "smaller than 5MB" and was just downloaded whole, but now the size is used. The server is reporting the gzipped size, unfortunately.

**Comment by jdldeauna** [comment]
Thanks for the help! I apologize, I thought the datasets were freely available and don't have log in credentials of any sort.

Would it be possible to apply for access? Or would access need to be funded by a project (if I'm understanding [requester-pays](https://cloud.google.com/storage/docs/requester-pays) correctly)?

**Comment by rabernat** [comment]
The data are freely available, but Google charges us [egress charges](https://blog.doit-intl.com/the-truth-behind-google-cloud-egress-traffic-6e8f57b5c2f8?gi=4db2301a82e0) for data that leaves the cloud. Our project cannot commit to paying the egress charges for everyone who wants to download the data. For example, before we had set up requester pays, we once got hit with a $1000 daily bill when someone downloaded the entire data catalog to Australia.

You have two options to get around this:
- Access the data from [Pangeo Cloud](https://pangeo.io/cloud.html) (free)
- Sign up for your own Google Cloud account. The [free tier](https://cloud.google.com/free) includes $300 of free credits. You can use this account (and the free credits) to provide a billing ID to pay the requester-pays egress charges.

**Comment by jdldeauna** [comment]
I see, thanks for the explanation! Again, sorry for misunderstanding how to access the data, I'll probably try to apply for a Pangeo Cloud account.
