### ISSUE TITLE
Some members with northward_wind, but not eastward_wind

### ISSUE THREAD

**Issue by juliettelavoie** [pangeo-data/pangeo-datastore#130]
In the cmip6-pds aws bucket, CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/ has 3 members (r1i1p1f1,r3i1p1f1,r4i1p1f1) that have both northward wind (`vas`) and eastward wind (`uas`).
 However, 50 members (r101i1p1f1 to r150i1p1f1) have `vas`, but not `uas`. 

Having only one component of the wind is not very practical... Is it possible that some data is missing from the bucket? Was there an issue when loading `uas`?

**Comment by naomi-henderson** [comment]
@juliettelavoie ,  this is puzzling. What I see are the following available datasets:
```
['s3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r11i1p1f1/Amon/uas/gr/v20200201/',
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r11i1p1f1/Amon/vas/gr/v20200201/',
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r13i1p1f1/Amon/uas/gr/v20200201/',
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r13i1p1f1/Amon/vas/gr/v20200201/',
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r15i1p1f1/Amon/uas/gr/v20200201/',
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r15i1p1f1/Amon/vas/gr/v20200201/',
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/uas/gr/v20200310/',
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/vas/gr/v20200310/',
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r3i1p1f1/Amon/uas/gr/v20210511/',
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r3i1p1f1/Amon/vas/gr/v20210511/',
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r4i1p1f1/Amon/uas/gr/v20200425/',
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r4i1p1f1/Amon/vas/gr/v20200425/',
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r6i1p1f1/Amon/uas/gr/v20200201/',
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r6i1p1f1/Amon/vas/gr/v20200201/',
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r9i1p1f1/Amon/uas/gr/v20200201/',
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r9i1p1f1/Amon/vas/gr/v20200201/']
```
Do you see something else?

**Comment by juliettelavoie** [comment]
Sorry I forgot to say that I was looking at daily frequency. For example, this one: https://cmip6-pds.s3.amazonaws.com/index.html#CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r101i1p1f1/day/ 

uas and vas:
['s3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/day/uas/gr/v20200310/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r4i1p1f1/day/uas/gr/v20200425/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r3i1p1f1/day/uas/gr/v20210511/']
['s3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/day/vas/gr/v20200310/',
's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r4i1p1f1/day/vas/gr/v20200425/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r3i1p1f1/day/vas/gr/v20210511/'] 

only vas:
 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r135i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r133i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r132i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r134i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r131i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r129i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r128i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r127i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r125i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r122i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r124i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r123i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r121i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r130i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r126i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r102i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r105i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r140i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r142i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r101i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r106i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r104i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r103i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r149i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r144i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r150i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r145i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r143i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r146i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r137i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r136i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r141i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r147i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r148i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r138i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r139i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r111i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r110i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r113i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r112i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r117i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r116i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r114i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r115i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r119i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r109i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r108i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r107i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r118i1p1f1/day/vas/gr/v20200412/', 's3://cmip6-pds/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r120i1p1f1/day/vas/gr/v20200412/']

**Comment by naomi-henderson** [comment]
Ah yes, so someone may have requested daily `vas` and did not need `uas`.  The zarr cloud collections have been populated almost completely by user requests.  If you would like to make a request, you can make it [here](https://docs.google.com/forms/d/e/1FAIpQLScFjA5IddqBs2Rc0xGbzn32NPq12TKr-b-8KGtXWyNDK5sJCg/viewform) - **at least until I retire next month**!  Be sure to specify which models/experiments/table/variables you want so the scripts can go to work on it.

**Comment by juliettelavoie** [comment]
ok thank you! Enjoy your last month of work!
