### ISSUE TITLE
Slow loading of datasets

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-datastore#22]
Our CI now reports on how long it takes each entry to execute `.to_dask()`. Here are the results, showing the slowest ones:

```
67.70s call     tests/validate_datasets.py::test_intake_dataset_to_dask[hydro.hydrosheds_dir]
41.35s call     tests/validate_datasets.py::test_intake_dataset_to_dask[atmosphere.trmm_3b42rt]
14.84s call     tests/validate_datasets.py::test_intake_dataset_to_dask[atmosphere.sam_ngaqua_qobs_eqx_3d]
7.12s call     tests/validate_datasets.py::test_intake_dataset_to_dask[atmosphere.gmet_v1]
6.50s call     tests/validate_datasets.py::test_intake_dataset_to_dask[cmip6.CNRM-CM6-1.historical.r2i1p1f2.huss]
5.02s call     tests/validate_datasets.py::test_intake_dataset_to_dask[cmip6.CNRM-ESM2-1.historical.r1i1p1f2.huss]
4.68s call     tests/validate_datasets.py::test_intake_dataset_to_dask[cmip6.IPSL-CM6A-LR.historical.r6i1p1f1.pr]
4.07s call     tests/validate_datasets.py::test_intake_dataset_to_dask[cmip6.GISS-E2-1-G.historical.r1i1p1f1.pr]
3.95s call     tests/validate_datasets.py::test_intake_dataset_to_dask[cmip6.CNRM-CM6-1.historical.r1i1p1f2.huss]
3.72s call     tests/validate_datasets.py::test_intake_dataset_to_dask[cmip6.CNRM-CM6-1.historical.r2i1p1f2.tas]
3.69s call     tests/validate_datasets.py::test_intake_dataset_to_dask[cmip6.CNRM-CM6-1.historical.r1i1p1f2.tas]
3.57s call     tests/validate_datasets.py::test_intake_dataset_to_dask[cmip6.CNRM-CM6-1.historical.r1i1p1f2.pr]
3.51s call     tests/validate_datasets.py::test_intake_dataset_to_dask[cmip6.IPSL-CM6A-LR.historical.r3i1p1f1.pr]
3.19s call     tests/validate_datasets.py::test_intake_dataset_to_dask[cmip6.IPSL-CM6A-LR.historical.r7i1p1f1.pr]
3.13s call     tests/validate_datasets.py::test_intake_dataset_to_dask[hydro.cgiar_pet]
...
```

I suspect that many of these are not using consolidated metadata. Consolidated metadata is now supported in xarray 0.12.0 and zarr 2.3.1. So we should use it on all our datasets.

Instructions for how to consolidate are here:
https://gist.github.com/rabernat/ce1fb414cf53541afe2245363b06c49d

It would be ideal of the owners of these datasets could run the consolidation themselves and update the catalog entries. But we don't know who the owners are, because of #19.

**Comment by naomi-henderson** [comment]
The cmip6 datasets are all with consolidated metadata - perhaps this is because these are the old entries (from cmip6.yaml) that were failing and it CI was reporting how long it took to fail?  Anyway, these old entries have now been deleted.

**Comment by jhamman** [comment]
I think we can list the owners of these datasets pretty easily.

@davidbrochart --> hydrosheds & cgiar
@jhamman --> gmet
@nbren12 - sam

It would be nice if we had an automated way to consolidate the metadata.

**Comment by rabernat** [comment]
> It would be nice if we had an automated way to consolidate the metadata.

We could do it from the CI if we had credentials.

**Comment by davidbrochart** [comment]
I uploaded the following datasets:
- `atmosphere.trmm_3b42rt`
- `hydro.hydrosheds_dir`
- `hydro.hydrosheds_acc`
- `hydro.cgiar_pet`

And GPM which is not in `pangeo-datastore`'s catalog (see https://github.com/pangeo-data/pangeo/issues/531#issuecomment-475802566).

None of these datasets have consolidated metadata.

**Comment by jhamman** [comment]
I ran @rabernat's notebook on the gmet dataset:

```
gmet_v1
Original Speed
CPU times: user 754 ms, sys: 89.6 ms, total: 844 ms
Wall time: 9.25 s
Consolidated Speed
CPU times: user 358 ms, sys: 16.4 ms, total: 375 ms
Wall time: 2.81 s
```
