### ISSUE TITLE
Intake for STAC

### ISSUE THREAD

**Issue by martindurant** [pangeo-data/pangeo-datastore#4]
The example catalog is JSON and simple enough to understand: the "item" entries are datasets, and the standard says that there can be references to other catalogues too (assuming that the name of each is to be derived from the href, if not otherwise given. 

However, the item contents takes a bit more explaining, specifically, what Intake would do with this in converting to a data source entry:
```json
{
  "type": "Feature",
  "id": "dataset-duacs-rep-global-merged-allsat-phy-l4-v3-alt",
  "bbox": [-180, -90, 180, 90],
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [-180, -90],
        [-180, 90],
        [180, 90],
        [180, -90],
        [-180, -90]
      ]
    ]
  },
  "properties":{
    "datetime":"1993-01-01T00:00:00Z",
    "dtr:start_datetime":"1993-01-01T00:00:00Z",
    "dtr:end_datetime":"2017-05-15T00:00:00Z"
  },
  "links": [
    {
      "rel": "self",
      "href": "https://storage.googleapis.com/pangeo-stac/test/example-item.json"
    },
    {
      "rel": "parent",
      "href": "https://storage.googleapis.com/pangeo-stac/test/example-catalog.json"
    }
  ],
  "assets": {
    "zarr": {
      "href": "https://storage.googleapis.com/pangeo-data/dataset-duacs-rep-global-merged-allsat-phy-l4-v3-alt/.zmetadata",
      "title": "Zarr consolidated metadata"
    }
  }
}
```

- "type" clearly has a meaning, and presumably we would have different interpretations of what follows based on this.
- "geometry" is a special structure, presumably would go into the metadata and any special functionality on an intake-stac cat would be able to do something with this
- "properties" in this case are all datetimes, which is only inferred by seeing them, but presumably this could be used in filtering too
- The zarr asset has key "zarr", so we know what driver to use here, and presumably there's a limited set of types we can understand. Is it normal for one item to have multiple entries here? I wonder, why is this pointing to the .zmetadata file rather than the directory?  (also, the ref is http rather than gcs, will this always be the case?)

**Comment by rabernat** [comment]
Just to be clear, I just totally invented the "assets" section as there was no guidance on how to represent zarr assets in STAC. We could change that completely. See discussion in https://github.com/radiantearth/stac-spec/issues/366.

The overall STAC spec is derived from geo-json: http://geojson.org/

Here is an interactive STAC browser: https://spacenet-stac.netlify.com/ The json info allows for a map view of collection.

**Comment by jhamman** [comment]
I know @martindurant and @rabernat are aware, but incase others come along, we've started work on https://github.com/pangeo-data/intake-stac.

**Comment by jhamman** [comment]
I'm going to close this as the intake-stac and [esm-collection-spec](https://github.com/NCAR/esm-collection-spec/tree/master/collection-spec) projects cover all the bases here.
