### ISSUE TITLE
Licenses for data

### ISSUE THREAD

**Issue by nbren12** [pangeo-data/pangeo-datastore#47]
Hey! Some recent experiences have taught me that data licensing might be important. Without a license it is hard/impossible to know how we can use a given dataset. The sort of open data-sharing that we are used to as climate scientists is actually operating in a legal gray area. Has a standardized approach to adding a license to pangeo data catalog entry been considered? For instance, CMIP data has a `license` attribute in their netCDF files. Many public data repositories like Zenodo use [Creative Commons licenses](https://creativecommons.org/licenses/).

**Comment by naomi-henderson** [comment]
Good point.  Here is a case to consider. 

When we convert CMIP6 netcdf files to zarr stores we do keep the `license` attribute in each and every store (in a text file called .zmetadata ) that we upload to the Google Cloud. According to the [CMIP6: Terms of Use](https://pcmdi.llnl.gov/CMIP6/TermsOfUse/TermsOfUse6-1.html) , we also must cite the appropriate document whenever publishing science based on these datasets. So, in my case, I am uploading notebooks to github explaining how to access the Pangeo GCS CMIP6 bucket, so I include something like the following at the top of such notebooks:

```
N.B. Please follow the guidelines given here:
    https://pcmdi.llnl.gov/CMIP6/TermsOfUse/TermsOfUse6-1.html 
for using and citing the CMIP6 data. 

We have preserved the license attribute/key from the original netcdf files in each zarr store. 
```

What do you all think? Is this sufficient? Is it needed at all in a jupyter notebook on github?

**Comment by nbren12** [comment]
I am not sure if that's enough, but it is better than I have been doing for the data I have contributed. Does anyone have thoughts if the license information live in the intake catalog, the zarr metadata, or both?
