### ISSUE TITLE
Joint Pangeo / STAC Video Call Scheduling

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-datastore#5]
As discussed in https://github.com/radiantearth/stac-spec/issues/366, we are setting up a video call to discuss how STAC might interoperate with Zarr / netCDF type data in the cloud.

 I have created a doodle poll for anyone interested in participating:

https://doodle.com/poll/eamhnih9y2kq5498

The options are for the week of Feb 4-8 and are chosen to be bi-coastal friendly. I will host the call via Zoom.

**Comment by m-mohr** [comment]
Thanks, unfortunately most of the times are quite late for Europe (5-11pm).

**Comment by rabernat** [comment]
Hi Mattias - Your presence is of course crucial. I'm sorry about the inconvenience with European time. This is always a challenge with Pangeo calls as well, since we have collaborators in Europe and West Coast US. 9 hours of time difference ensure that some one has to do the call outside of normal business hours. In my experience, it is more likely that someone from Europe is available 5-7pm than someone from the west coast is available from 6-8am. But I apologize for the inconvenience this causes.

In the doodle, you indicated two times on Wednesday that work for you. Is this still accurate? If so, we will hope these times work for the rest of the group. If not, I will cancel the poll and start over.

**Comment by m-mohr** [comment]
I am aware of the problem, of course. We have the same problems with the STAC calls, but it seems 10.30 EST seems to work quite well.

Unfortunately, only on Monday your mentioned time frame from 5 to 7pm is actually in the doodle and on Monday I have other obligations, unfortunately. I'm still available on Wednesday.

**Comment by rabernat** [comment]
Final time has been chosen

Topic: STAC / Pangeo NetCDF Discussion
Time: Feb 6, 2019 2:00 PM Eastern Time (US and Canada)

Join Zoom Meeting
https://columbiauniversity.zoom.us/j/838989507

One tap mobile
+16468769923,,838989507# US (New York)
+16699006833,,838989507# US (San Jose)

Dial by your location
+1 646 876 9923 US (New York)
+1 669 900 6833 US (San Jose)
Meeting ID: 838 989 507
Find your local number: https://zoom.us/u/abIn8fRWIF

**Comment by rabernat** [comment]
Tentative agenda for today

- Introductions (~20 minutes):
    - What do you work on? What is your interest in the call? 2-3 minute per person. (This is a good place to explain the tech you work on, e.g. netCDF, THREDDS, opendap, zarr, etc.)
- STAC Overview - Chris Holmes (~5 minutes)
- Brainstorm (~30 minutes)

Guiding Questions: 

I have 1000 netCDF files in cloud storage. How do I catalog them today / tomorrow?
I have a several large zarr arrays in cloud storage. How do I catalog them today / tomorrow?

Additional Prompts: 

- What is the 'static catalog' for netCDF look like? 
  - STAC / TDS XML / how do they interact, how do you switch between them?
  - How do we bridge STAC and netCDF world?
  - Mapping between STAC and TDS?
  - Hyrex / THREDDS implement STAC API?
  - STAC Extension for nD data? What does this look like?
  - STAC Browser / Google Dataset Search format?
  - Change STAC core data model in some way for many items with one asset
- How do we point to a zarr "file" in STAC considering that it is actually a nested directory structure?

Wrap up (~5 minutes)

Next Steps and TODO's

**Comment by rabernat** [comment]
Thanks to everyone who participated in the call.

There is some relevant discussion happening in #3, where we are deliberating how existing standards (e.g. ISO metadata, OGC CSW) might help us achieve our goals.

**Comment by kmpaul** [comment]
Should this issue be closed?
