### ISSUE TITLE
Add some cloud fraction data?

### ISSUE THREAD

**Issue by nickLN** [pangeo-data/pangeo-datastore#60]
Hey all,
I'm pretty new to using git but I have cloud fraction data downloaded and I want to compare it to air temperature and then I saw that it was available to use on pangeo! It doesn't look like cloud fraction data is available however, and I was wondering when/if more 3D fields like historical cloud fraction data would be available to pull from the datastore?

Cheers

**Comment by sebastienlanglois** [comment]
Hi @nickLN ,

ERA5 reanalysis is being uploaded right now in the .zarr format and should be available in about a week on pangeo. Data will be available at an hourly time step from 1979 to 2018.

It contains a variable called **Total Cloud Cover**, which is a fraction between 0 and 1. More documentation can be found in the following link :
https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=doc

Does this correspond to what you are looking for?
