### ISSUE TITLE
Switch to requester-pays

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-datastore#63]
In order to activate requester-pays, we need to
- [ ] use gcsfs >= 0.5.1 (https://gcsfs.readthedocs.io/en/latest/changelog.html#version-0-5-1)
- [ ] remove the `storage_options: token: anon` part from the intake entry

@charlesbluca - could you try out making these changes to some of the existing datasets.

**Comment by TomAugspurger** [comment]
xref https://github.com/pangeo-data/pangeo-datastore/pull/61.

**Comment by rabernat** [comment]
Ah thanks Tom, I had not caught that there was already an issue on this. Closing in favor of #61.
