### ISSUE TITLE
move datasets out of pangeo-data

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-datastore#64]
As discussed in https://discourse.pangeo.io/t/cleaning-out-the-pangeo-data-google-cloud-storage-bucket/353, we would like to retire the pangeo-data bucket in favor of more specific buckets. There should be one bucket per dataset / collection.

The order of operations should be:
1. Copy the dataset to its new bucket (set as requester pays)
2. Update the intake catalog an ensure that it works in the new location
3. Delete the copy from `pangeo-data`

Would be great if @charlesbluca could look into this.

**Comment by charlesbluca** [comment]
Do we want any sort of nomenclature for these new containing buckets, or should they just match up with the names of the original datasets?

**Comment by rabernat** [comment]
We don't have a convention here yet. Anything reasonable will do. Buckets have very restrictive naming conventions that we will have to follow.

**Comment by charlesbluca** [comment]
Okay, I'll start the move using buckets with the same config as pangeo-data -- we can work out bucket-level configuration as we move forward.

**Comment by rabernat** [comment]
Be careful with how you move the data. You don't want to incur egress charges.

https://cloud.google.com/storage/docs/moving-buckets

You probably want to do this from the google cloud shell.

**Comment by charlesbluca** [comment]
To avoid any unnecessary bucket transfers, here's an overview of the transfers taking place - we can work out proper bucket names for some of the datasets with more problematic names (bucket names containing periods require verification).

Once we have the naming out the way, it shouldn't take too long to queue up the transfers:

| dataset(s)                                        | original location                                                          | new location                                               |
| ------------------------------------------------- | -------------------------------------------------------------------------- | ---------------------------------------------------------- |
| cesm_mom6_example                                 | gcs://pangeo-data/MOM6.cesm                                                | gcs://mom6-cesm                                            |
| CESM_POP_hires_control                            | gcs://pangeo-data/cesm/hybrid_v5_rel04_BC5_ne120_t12_pop62                 | gcs://cesm-pop                                             |
| CESM_POP_hires_RCP8_5                             | gcs://pangeo-data/cesm/BRCP85C5CN_ne120_t12_pop62.c13b17.asdphys.001       | gcs://cesm-pop                                             |
| cgiar_pet                                         | gcs://pangeo-data/cgiar_pet                                                | gcs://cgiar-pet                                            |
| ECCO_layers                                       | gcs://pangeo-data/ECCO_layers.zarr                                         | gcs://pangeo-ecco                                          |
| ECCOv4r3                                          | gcs://pangeo-data/ecco/eccov4r3                                            | gcs://pangeo-ecco                                          |
| GFDL_CM2_6_control_ocean                          | gcs://pangeo-data/cm2.6/control/ocean                                      | gcs://gfdl-cm26                                            |
| GFDL_CM2_6_control_ocean_3D                       | gcs://pangeo-data/cm2.6/control/temp_salt_u_v-5day_avg                     | gcs://gfdl-cm26                                            |
| GFDL_CM2_6_control_ocean_boundary_flux            | gcs://pangeo-data/cm2.6/control/ocean_bdy_flux                             | gcs://gfdl-cm26                                            |
| GFDL_CM2_6_control_ocean_surface                  | gcs://pangeo-data/cm2.6/control/surface_daily                              | gcs://gfdl-cm26                                            |
| GFDL_CM2_6_control_ocean_transport                | gcs://pangeo-data/cm2.6/control/ocean_trans                                | gcs://gfdl-cm26                                            |
| GFDL_CM2_6_grid                                   | gcs://pangeo-data/cm2.6/grid                                               | gcs://gfdl-cm26                                            |
| GFDL_CM2_6_one_percent_ocean                      | gcs://pangeo-data/cm2.6/one_percent/ocean                                  | gcs://gfdl-cm26                                            |
| GFDL_CM2_6_one_percent_ocean_3D                   | gcs://pangeo-data/cm2.6/one_percent/temp_salt_u_v-5day_avg                 | gcs://gfdl-cm26                                            |
| GFDL_CM2_6_one_percent_ocean_boundary_flux        | gcs://pangeo-data/cm2.6/one_percent/ocean_bdy_flux                         | gcs://gfdl-cm26                                            |
| GFDL_CM2_6_one_percent_ocean_surface              | gcs://pangeo-data/cm2.6/one_percent/surface_daily                          | gcs://gfdl-cm26                                            |
| GFDL_CM2_6_one_percent_ocean_transport            | gcs://pangeo-data/cm2.6/one_percent/ocean_trans                            | gcs://gfdl-cm26                                            |
| gmet_v1                                           | gcs://pangeo-data/gmet_v1.zarr                                             | gcs://gmet-v1                                              |
| GODAS                                             | gcs://pangeo-data/GODAS/zarr                                               | gcs://godas                                                |
| gpcp_cdr_daily_v1_3                               | gcs://pangeo-data/GPCP_CDR_Daily_V1.3                                      | gcs://gpcp-cdr-daily-v13                                   |
| hydrosheds_acc                                    | gs://pangeo-data/hydrosheds/acc.vrt                                        | gs://hydrosheds                                            |
| hydrosheds_dem                                    | gs://pangeo-data/hydrosheds/dem.vrt                                        | gs://hydrosheds                                            |
| hydrosheds_dir                                    | gs://pangeo-data/hydrosheds/dir.vrt                                        | gs://hydrosheds                                            |
| LLC4320_grid                                      | gcs://pangeo-data/llc4320_surface/grid                                     | gcs://llc4320                                              |
| LLC4320_SSH                                       | gcs://pangeo-data/llc4320_surface/Eta                                      | gcs://llc4320                                              |
| LLC4320_SSS                                       | gcs://pangeo-data/llc4320_surface/SSS                                      | gcs://llc4320                                              |
| LLC4320_SST                                       | gcs://pangeo-data/llc4320_surface/SST                                      | gcs://llc4320                                              |
| LLC4320_SSU                                       | gcs://pangeo-data/llc4320_surface/U                                        | gcs://llc4320                                              |
| LLC4320_SSV                                       | gcs://pangeo-data/llc4320_surface/V                                        | gcs://llc4320                                              |
| MITgcm_channel_flatbottom_02km_run01_phys-mon     | gcs://pangeo-data/takaya/MITgcm-channel-flatbottom-02km-run01/phys-mon     | gcs://mitgcm                                               |
| MITgcm_channel_flatbottom_02km_run01_phys_snap15D | gcs://pangeo-data/takaya/MITgcm-channel-flatbottom-02km-run01/phys-snap15D | gcs://mitgcm                                               |
| sam_ngaqua_qobs_eqx_2d                            | gcs://pangeo-data/SAM/NG_5120x2560x34_4km_10s_QOBS_EQX/2d.zarr             | gcs://sam-ngaqua-qobs-eqx                                  |
| sam_ngaqua_qobs_eqx_3d                            | gcs://pangeo-data/SAM/NG_5120x2560x34_4km_10s_QOBS_EQX/3d.zarr             | gcs://sam-ngaqua-qobs-eqx                                  |
| sea_surface_height                                | gcs://pangeo-data/dataset-duacs-rep-global-merged-allsat-phy-l4-v3-alt     | gcs://dataset-duacs-rep-global-merged-allsat-phy-l4-v3-alt |
| SOSE                                              | gcs://pangeo-data/SOSE                                                     | gcs://sose                                                 |
| trmm_3b42rt                                       | gcs://pangeo-data/trmm_3b42rt                                              | gcs://trmm-3b42rt                                          |
| wrf50_erai                                        | gcs://pangeo-data/ncar_wrf50/erai.wrf_daily_data.zarr                      | gcs://wrf50-erai                                           |

**Comment by rabernat** [comment]
I think all the bucket names should start with `pangeo-`.

**Comment by charlesbluca** [comment]
Good catch! Edited to reflect this.

**Comment by rabernat** [comment]
What if we use some sort of convention for the bucket names like

`pangeo-[organization_id]-[dataset_id]`

Where `[oragnization_id]` is an identifier for whoever produced the original data and `[dataset_id]` is an identifier for the dataset.

So for llc: `pangeo-ecco-llc4320`, etc.

It's nice having the table here on github, but if you turned it into a google sheet, I could make suggestions more easily.

**Comment by charlesbluca** [comment]
Good idea - made a Google sheet of the table [here](https://docs.google.com/spreadsheets/d/1X0zaHX2y1Cn6ki1BaiTqytmZFIeo8ovirJeBLCE554s/edit?usp=sharing).

Let me know if you have trouble accessing this.

**Comment by rabernat** [comment]
Charles I think there is something wrong with this spreadsheet. If I try to edit a cell, the whole rest of the sheet disappears. Did you experience this?

**Comment by charlesbluca** [comment]
Should be fixed now.

**Comment by rabernat** [comment]
I created a second sheet in that spreadsheet with my recommended renaming.

**Comment by rabernat** [comment]
If you agree with how I renamed things, you can go ahead and start moving data over! Let's try the process on just the first dataset (cesm-mom6) and see how it goes.

**Comment by charlesbluca** [comment]
It seems like I need `serviceusage.services.use` access to specify the project when performing the move:

```
>> gsutil -u pangeo-181919 -m cp -r gs://pangeo-data/MOM6.cesm/* gs://pangeo-cesm-mom6
AccessDeniedException: 403 ccb2158@columbia.edu does not have serviceusage.services.use access to project 464800473488.
CommandException: 1 file/object could not be transferred.
```

**Comment by rabernat** [comment]
try removing `-u pangeo-181919`

**Comment by charlesbluca** [comment]
In that case, it says a user project must be specified:

```
BadRequestException: 400 Bucket is requester pays bucket but no user project provided.
```

**Comment by rabernat** [comment]
Charles--sorry for the delay in replying. I have granted you `project.editor` on the pangeo project, so you should now be able to do whatever you want. Use with care! 😉

**Comment by charlesbluca** [comment]
After moving the datasets for CESM-MOM6 to their new bucket and adding it to an Intake catalog, I got an `HTTPError` when trying `to_dask()` - it looks like the user project must be provided in order to access a dataset within a requester pays bucket.

**Comment by rabernat** [comment]
> it looks like the user project must be provided in order to access a dataset within a requester pays bucket.

Correct. But that should all be possible now, given the recent updates to gcsfs.

**Comment by rabernat** [comment]
@charlesbluca - are you still stuck on this? @TomAugspurger fixed dealt with the gcsfs issues in https://github.com/dask/gcsfs/pull/206 and https://github.com/dask/gcsfs/pull/208. He may be able to give you some advice.

I think you just have to remove `token='anon'` from the intake entry and everything should work.

**Comment by TomAugspurger** [comment]
https://github.com/dask/gcsfs/issues/216#issuecomment-561885208 also has an example.

And just a heads up, I *may* have to change the API for requester pays: https://github.com/dask/gcsfs/issues/218. Still investigating, but it may need to be `GCSFileSystem(..., requester_pays=True)`, i.e. and explicit opt in, rather than falling back to the `project`. For some reason including the `?project=my_project` in every request is giving authentication errors for some users.

**Comment by charlesbluca** [comment]
Looks like it was an issue of authentication - everything works fine when I make an instance of `GCSFileSystem` with the user project properly defined before using `to_dask()`. In that case, I will begin moving forward with the data transfer.

**Comment by gmaze** [comment]
Hi folks,
It seems that since this morning the AVISO sea_surface_height product has been moved or removed from ```gs://pangeo-data/dataset-duacs-rep-global-merged-allsat-phy-l4-v3-alt```
Is this permanent or temporary ?
thanks
g

**Comment by charlesbluca** [comment]
This will be a permanent move of the `sea_surface_height` to its own requester pays bucket located at `gs://pangeo-cmems-duacs`. While we are still in the process of reflecting this change within the intake catalogs, alternatives for accessing the relocated data can be found in #74.

**Comment by rabernat** [comment]
@guillaumeeb - really sorry about this. Our plan was to do things in such a way that it would not interrupt users, but something went wrong. We are trying to sort it out in https://github.com/pangeo-data/pangeo-datastore/pull/67.

**Comment by gmaze** [comment]
Ok guys, this is good to know, I understand the change.

**Comment by rabernat** [comment]
@gmaze - this should now be fixed, provided you access the data from the intake catalog (rather than with an explicit path).

**Comment by gmaze** [comment]
Thanks @rabernat . Looks ok from the catalog, given the new access policy on a requester_pays basis, right ?
