### ISSUE TITLE
Help deploying dynamic pangeo-datastore

### ISSUE THREAD

**Issue by charlesbluca** [pangeo-data/pangeo-datastore#65]
As discussed in this week's check-in, I have been working on a dynamic version of the Pangeo Data Catalog, in the form of a Flask app to be deployed through Google App Engine. Ideally, I'd like to get some form of CI so that we can edit the source code here on Github and have changes automatically redeployed.

I'm new to both Flask and CI, and could use some help getting started on this. @jbednar, you said you had a lot of experience working with both - are there any templates or guides you could direct me to? The current source code for the site is [here](https://github.com/charlesbluca/pangeo-datastore-flask).

**Comment by TomAugspurger** [comment]
For my own understanding, can you share a bit more about what we get by using Flask, that we can't achieve with the current static site? I'm sure you mentioned it on the call, but I've forgotten.

> Ideally, I'd like to get some form of CI so that we can edit the source code here on Github and have changes automatically redeployed.

IIUC, the Flask app wouldn't need to be redeployed based on changes to the catalog. Rather, the app would build things on each request / interaction from the user.

**Comment by charlesbluca** [comment]
The main motivation behind moving to a dynamic website would be scalability - currently, the entire website gets rebuilt for any change made to the catalogs, which becomes problematic as the catalog size increases or if additions/changes become frequent.

What I have in mind is a standalone repository for the online catalog app, which is only redeployed when the source code (i.e. Jinja2 templates, server-side Python) is altered - this will point to some hierarchy of Intake catalogs stored in a separate location (such as this repository), eliminating the need to redeploy whenever the catalog is changed.

**Comment by TomAugspurger** [comment]
Thanks. I didn't appreciate how long generating the current site took. I assumed it was just loading / manipulating a bit of JSON and rendering, but that's clearly not the case.

> currently, the entire website gets rebuilt for any change made to the catalogs, which becomes problematic as the catalog size increases or if additions/changes become frequent.

In theory, we could detect which catalog has changed and only re-render those. I think we would need include the output of `build_catalog_rst.py` in the git repo though.

---

Can you clarify why you think you'd need to redeploy the web app based on changes elsewhere? In my mind, the benefit of the web app is that it's dynamic and can do things based on user requests. Ideally we could point the app at an arbitrary URL and have it extract the information needed to render catalog, no deployment needed. Does that make sense?

**Comment by rabernat** [comment]
> Can you clarify why you think you'd need to redeploy the web app based on changes elsewhere? In my mind, the benefit of the web app is that it's dynamic and can do things based on user requests. Ideally we could point the app at an arbitrary URL and have it extract the information needed to render catalog, no (re)deployment needed. Does that make sense?

This is what I thought would be the case. The app loads the intake catalog dynamically, on the fly. The app doesn't have to be redeployed if the catalog changes--only if the app code itself changes (which will happen frequently as we develop it).

> In theory, we could detect which catalog has changed and only re-render those.

I would like to do something like this for the catalog CI, i.e. only run the checks on the catalog diff, rather than the whole catalog.

**Comment by TomAugspurger** [comment]
Cool, I think we're on the same page then.

@charlesbluca let me know if you want to chat later today / next week about this. I have a bit of web dev experience.

**Comment by charlesbluca** [comment]
Would love to chat about this later today! Excited to get the ball rolling on this one.

**Comment by TomAugspurger** [comment]
OK, I should be free any time from ~1:00 - 4:00 Central time. Any time in there work for you? We can meet in whereby.com/pangeo

**Comment by charlesbluca** [comment]
Sure, how does 3 sound to you?

**Comment by TomAugspurger** [comment]
3 Central (2 hours from now)? That works for me.

**Comment by charlesbluca** [comment]
Based on the call, I'll be looking into [Celery](https://blog.miguelgrinberg.com/post/using-celery-with-flask) to push off the process of loading and presenting datasets to be request-based (ideally when a user opens an "xarray preview" panel) - thank @TomAugspurger!

As for the CI, it looks like [this guide](https://cloud.google.com/cloud-build/docs/run-builds-on-github) seems to accomplish what we'd like for this, but it relies on Cloud Build which is limited to 120 free build-hours per day. This could be sufficient for our needs - just putting it out there.

**Comment by rabernat** [comment]
Awesome work guys! Thanks @charlesbluca for taking the initiative to set up this call and @TomAugspurger for suggesting a path forward. I think this Celery idea is cool idea for firing of tasks dynamically. I'm not quite sure why Flask by itself is not up to the task, but I trust you guys have thought it through. All else being equal, best not to introduce a new tool into our system, as it increases complexity.

Not too familiar with cloud-build. Is it similar to travis / circleci? My preference is to use free CI tools as much as we can, but as you said, if we stay under the usage limits, cb would not be a problem.

What about deploying the flask app with CI? Is that something we can accomplish with regular travis / circle type CI?
