### ISSUE TITLE
Data Management TWG - Mission Statement

### ISSUE THREAD

**Issue by darothen** [pangeo-data/pangeo-datastore#7]
We'd like to craft a mission statement for the data management technical working group in order to clarify some tangible things we should aim to produce for the community. The best way to do this will probably be as simple Markdown document which we can add to this or a similar repository. In the meantime, I'd like to brainstorm themes for the mission statement before drafting it.

Based on our past discussions, it seems like there are a few major themes relating to knowledge/tooling gaps regarding data management:

1. Broader catalog of cloud-optimized data stores, relating to real scientific use cases
2. Tooling for converting/optimizing data sets for the cloud, and "best practices" therein
3. Cataloging tools
4. Interfaces similar to THREDDS/OPeNDAP for accessing cloud-optimized datastores

(2) and (3) have had significant work from community members, with projects like [Intake](https://intake.readthedocs.io/en/latest/) seriously moving the ball down the field towards the goal. Thematically, our mission statement should indicate where we think a reasonable finish line is for this work, based on our understanding of stakeholder needs in the geosciences community. We're particularly interested in (1) and (4) as our "tangible" deliverable... real data sitting behind easily accessible APIs or gateways, in addition to the direct xarray/zarr-based access we use in Pangeo demos.

Let's solicit comments here, then ultimately move to a PR with a plaintext, simple document.

**Comment by rabernat** [comment]
Thanks for spearheading this! I think it will be great to have a clearly defined scope for our working group.

Here is a stab at a mission statement.

> Our mission is to define a set of best practices around to "cloud native climate data." These practices include (a) the creation of cloud-optimized datasets, (b) cataloging cloud-based datasets, (c) user-facing services for interacting with these datasets and catalogs. As much as possible, this work should leverage existing standards and technologies, focusing innovation wherever cloud technology requires a departure from legacy practices.

**Comment by ktyle** [comment]
Good start @rabernat . Maybe generalize beyond just "climate" data ... how about "weather and climate data"?
