### ISSUE TITLE
cannot import data from intake-catalogs

### ISSUE THREAD

**Issue by hmkhatri** [pangeo-data/pangeo-datastore#73]
I have been working with MITgcm run LLC4320 for some time and I always read the grid file in the following way 
cat = intake.Catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean/llc4320.yaml")
dsgrid = cat["LLC4320_grid"].to_dask()

For some reason, the command is not working anymore. I get the following error.

HTTPError: 404 Client Error: Not Found for url: https://www.googleapis.com/download/storage/v1/b/pangeo-data/o/llc4320_surface%2Fgrid%2F.zmetadata?alt=media
During handling of the above exception, another exception occurred:

In fact, I tried other examples given on "https://pangeo-data.github.io/pangeo-datastore/index.html". None of them worked. 

Could you please help with this?

Thanks
Hemant

**Comment by TomAugspurger** [comment]
Can you post the full traceback?

**Comment by hmkhatri** [comment]
Here is the complete error,

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/mapping.py in __getitem__(self, key, default)
     75         try:
---> 76             result = self.fs.cat(key)
     77         except:  # noqa: E722

</srv/conda/envs/notebook/lib/python3.7/site-packages/decorator.py:decorator-gen-129> in cat(self, path)

/srv/conda/envs/notebook/lib/python3.7/site-packages/gcsfs/core.py in _tracemethod(f, self, *args, **kwargs)
     49 
---> 50     return f(self, *args, **kwargs)
     51 

/srv/conda/envs/notebook/lib/python3.7/site-packages/gcsfs/core.py in cat(self, path)
    844         r = self.session.get(u2)
--> 845         r.raise_for_status()
    846         if "X-Goog-Hash" in r.headers:

/srv/conda/envs/notebook/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 

HTTPError: 404 Client Error: Not Found for url: https://www.googleapis.com/download/storage/v1/b/pangeo-data/o/llc4320_surface%2Fgrid%2F.zmetadata?alt=media

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-1-e37d3ad015c3> in <module>
      1 import intake
      2 cat = intake.Catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean/llc4320.yaml")
----> 3 ds = cat["LLC4320_grid"].to_dask()

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_xarray/base.py in to_dask(self)
     67     def to_dask(self):
     68         """Return xarray object where variables are dask arrays"""
---> 69         return self.read_chunked()
     70 
     71     def close(self):

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_xarray/base.py in read_chunked(self)
     42     def read_chunked(self):
     43         """Return xarray object (which will have chunks)"""
---> 44         self._load_metadata()
     45         return self._ds
     46 

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake/source/base.py in _load_metadata(self)
    115         """load metadata only if needed"""
    116         if self._schema is None:
--> 117             self._schema = self._get_schema()
    118             self.datashape = self._schema.datashape
    119             self.dtype = self._schema.dtype

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_xarray/base.py in _get_schema(self)
     16 
     17         if self._ds is None:
---> 18             self._open_dataset()
     19 
     20             metadata = {

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_xarray/xzarr.py in _open_dataset(self)
     29 
     30         self._mapper = get_mapper(self.urlpath, **self.storage_options)
---> 31         self._ds = xr.open_zarr(self._mapper, **self.kwargs)
     32 
     33     def close(self):

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/backends/zarr.py in open_zarr(store, group, synchronizer, chunks, decode_cf, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, consolidated, overwrite_encoded_chunks, **kwargs)
    594         synchronizer=synchronizer,
    595         group=group,
--> 596         consolidated=consolidated,
    597     )
    598     ds = maybe_decode_store(zarr_store)

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/backends/zarr.py in open_group(cls, store, mode, synchronizer, group, consolidated, consolidate_on_close)
    256         if consolidated:
    257             # TODO: an option to pass the metadata_key keyword
--> 258             zarr_group = zarr.open_consolidated(store, **open_kwargs)
    259         else:
    260             zarr_group = zarr.open_group(store, **open_kwargs)

/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/convenience.py in open_consolidated(store, metadata_key, mode, **kwargs)
   1180 
   1181     # setup metadata sotre
-> 1182     meta_store = ConsolidatedMetadataStore(store, metadata_key=metadata_key)
   1183 
   1184     # pass through

/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/storage.py in __init__(self, store, metadata_key)
   2455             d = store[metadata_key].decode()  # pragma: no cover
   2456         else:  # pragma: no cover
-> 2457             d = store[metadata_key]
   2458         meta = json_loads(d)
   2459 

/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/mapping.py in __getitem__(self, key, default)
     78             if default is not None:
     79                 return default
---> 80             raise KeyError(key)
     81         return result
     82 

KeyError: 'pangeo-data/llc4320_surface/grid/.zmetadata'

**Comment by TomAugspurger** [comment]
This may be related to the work @charlesbluca is doing in https://github.com/pangeo-data/pangeo-datastore/pull/67, specifically https://github.com/pangeo-data/pangeo-datastore/pull/67/files#diff-c6a404d5370aaf828c8acb54a9fc528b. Those files may be in the `pangeo-ecco-llc4320` bucket now.

**Comment by hmkhatri** [comment]
Thanks, Tom.

I created a LLC4320.yaml file in my home directory with the updated url. However, I am still getting an error (full error traceback is at the end).  Is it related to the discussion about "requester_pays" option on #67 .

I used the following commands,
import intake
cat = intake.Catalog("/home/jovyan/LLC4320.yaml")
ds = cat["LLC4320_grid"].to_dask()

My .yaml file is,
-----------------------
plugins:
  source:
    - module: intake_xarray
sources:
  LLC4320_grid:
    description: MITgcm LLC4320 Ocean Simulation Grid
    metadata:
      url: 'http://online.kitp.ucsb.edu/online/blayers18/menemenlis/'
      tags:
        - ocean
        - model
    driver: zarr
    args:
      urlpath: gs://pangeo-ecco-llc4320/grid
      consolidated: True
-------------------------

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/mapping.py in __getitem__(self, key, default)
     75         try:
---> 76             result = self.fs.cat(key)
     77         except:  # noqa: E722

</srv/conda/envs/notebook/lib/python3.7/site-packages/decorator.py:decorator-gen-129> in cat(self, path)

/srv/conda/envs/notebook/lib/python3.7/site-packages/gcsfs/core.py in _tracemethod(f, self, *args, **kwargs)
     49 
---> 50     return f(self, *args, **kwargs)
     51 

/srv/conda/envs/notebook/lib/python3.7/site-packages/gcsfs/core.py in cat(self, path)
    844         r = self.session.get(u2)
--> 845         r.raise_for_status()
    846         if "X-Goog-Hash" in r.headers:

/srv/conda/envs/notebook/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 

HTTPError: 400 Client Error: Bad Request for url: https://www.googleapis.com/download/storage/v1/b/pangeo-ecco-llc4320/o/grid%2F.zmetadata?alt=media

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-5-07450f2785ea> in <module>
----> 1 ds = cat["LLC4320_grid"].to_dask()

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_xarray/base.py in to_dask(self)
     67     def to_dask(self):
     68         """Return xarray object where variables are dask arrays"""
---> 69         return self.read_chunked()
     70 
     71     def close(self):

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_xarray/base.py in read_chunked(self)
     42     def read_chunked(self):
     43         """Return xarray object (which will have chunks)"""
---> 44         self._load_metadata()
     45         return self._ds
     46 

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake/source/base.py in _load_metadata(self)
    115         """load metadata only if needed"""
    116         if self._schema is None:
--> 117             self._schema = self._get_schema()
    118             self.datashape = self._schema.datashape
    119             self.dtype = self._schema.dtype

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_xarray/base.py in _get_schema(self)
     16 
     17         if self._ds is None:
---> 18             self._open_dataset()
     19 
     20             metadata = {

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_xarray/xzarr.py in _open_dataset(self)
     29 
     30         self._mapper = get_mapper(self.urlpath, **self.storage_options)
---> 31         self._ds = xr.open_zarr(self._mapper, **self.kwargs)
     32 
     33     def close(self):

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/backends/zarr.py in open_zarr(store, group, synchronizer, chunks, decode_cf, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, consolidated, overwrite_encoded_chunks, **kwargs)
    594         synchronizer=synchronizer,
    595         group=group,
--> 596         consolidated=consolidated,
    597     )
    598     ds = maybe_decode_store(zarr_store)

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/backends/zarr.py in open_group(cls, store, mode, synchronizer, group, consolidated, consolidate_on_close)
    256         if consolidated:
    257             # TODO: an option to pass the metadata_key keyword
--> 258             zarr_group = zarr.open_consolidated(store, **open_kwargs)
    259         else:
    260             zarr_group = zarr.open_group(store, **open_kwargs)

/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/convenience.py in open_consolidated(store, metadata_key, mode, **kwargs)
   1180 
   1181     # setup metadata sotre
-> 1182     meta_store = ConsolidatedMetadataStore(store, metadata_key=metadata_key)
   1183 
   1184     # pass through

/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/storage.py in __init__(self, store, metadata_key)
   2455             d = store[metadata_key].decode()  # pragma: no cover
   2456         else:  # pragma: no cover
-> 2457             d = store[metadata_key]
   2458         meta = json_loads(d)
   2459 

/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/mapping.py in __getitem__(self, key, default)
     78             if default is not None:
     79                 return default
---> 80             raise KeyError(key)
     81         return result
     82 

KeyError: 'pangeo-ecco-llc4320/grid/.zmetadata'

**Comment by TomAugspurger** [comment]
This worked for me locally

```python
In [3]:  import intake
   ...: cat = intake.Catalog("LLC4320.yaml")
   ...: ds = cat["LLC4320_grid"].to_dask()
```

with the following catalog file

```yaml
plugins:
  source:
    - module: intake_xarray
sources:
  LLC4320_grid:
    description: MITgcm LLC4320 Ocean Simulation Grid
    metadata:
      url: 'http://online.kitp.ucsb.edu/online/blayers18/menemenlis/'
      tags:
        - ocean
        - model
    driver: zarr
    args:
      urlpath: gcs://pangeo-ecco-llc4320/grid
      consolidated: True
      storage_options:
          requester_pays: True
```

The important bits are

1. I added the `storage_options: requester_pays: True` part to the catalog. That's part of what https://github.com/pangeo-data/pangeo-datastore/pull/67 is doing.
2. I have my machine configured correctly to use my credentials. I'll provide more details on this later. There's a bit at https://gcsfs.readthedocs.io/en/latest/#credentials. I'm using the token generated by gcloud.

Now, when you're within google cloud (on our binder or our jupyterhub) you ideally wouldn't need to worry about requester pays. IIUC since the data and compute are in the same region there won't be any charges. But I'm not sure yet how to do that, or if it's possible.

**Comment by hmkhatri** [comment]
I tried with storage_options: requester_pays: True as a part of the catalog. However, this did not help. The error (see below) is the same irrespective of requester_pays: True is defined or not in the yaml file.

Is it possible to copy the grid file to my home directory on binder? The grid file is small in size and would not take much space. This could be a temporary solution for now.  

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/mapping.py in __getitem__(self, key, default)
     75         try:
---> 76             result = self.fs.cat(key)
     77         except:  # noqa: E722

</srv/conda/envs/notebook/lib/python3.7/site-packages/decorator.py:decorator-gen-129> in cat(self, path)

/srv/conda/envs/notebook/lib/python3.7/site-packages/gcsfs/core.py in _tracemethod(f, self, *args, **kwargs)
     49 
---> 50     return f(self, *args, **kwargs)
     51 

/srv/conda/envs/notebook/lib/python3.7/site-packages/gcsfs/core.py in cat(self, path)
    844         r = self.session.get(u2)
--> 845         r.raise_for_status()
    846         if "X-Goog-Hash" in r.headers:

/srv/conda/envs/notebook/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 

HTTPError: 400 Client Error: Bad Request for url: https://www.googleapis.com/download/storage/v1/b/pangeo-ecco-llc4320/o/grid%2F.zmetadata?alt=media

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-7-07450f2785ea> in <module>
----> 1 ds = cat["LLC4320_grid"].to_dask()

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_xarray/base.py in to_dask(self)
     67     def to_dask(self):
     68         """Return xarray object where variables are dask arrays"""
---> 69         return self.read_chunked()
     70 
     71     def close(self):

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_xarray/base.py in read_chunked(self)
     42     def read_chunked(self):
     43         """Return xarray object (which will have chunks)"""
---> 44         self._load_metadata()
     45         return self._ds
     46 

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake/source/base.py in _load_metadata(self)
    115         """load metadata only if needed"""
    116         if self._schema is None:
--> 117             self._schema = self._get_schema()
    118             self.datashape = self._schema.datashape
    119             self.dtype = self._schema.dtype

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_xarray/base.py in _get_schema(self)
     16 
     17         if self._ds is None:
---> 18             self._open_dataset()
     19 
     20             metadata = {

/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_xarray/xzarr.py in _open_dataset(self)
     29 
     30         self._mapper = get_mapper(self.urlpath, **self.storage_options)
---> 31         self._ds = xr.open_zarr(self._mapper, **self.kwargs)
     32 
     33     def close(self):

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/backends/zarr.py in open_zarr(store, group, synchronizer, chunks, decode_cf, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, consolidated, overwrite_encoded_chunks, **kwargs)
    594         synchronizer=synchronizer,
    595         group=group,
--> 596         consolidated=consolidated,
    597     )
    598     ds = maybe_decode_store(zarr_store)

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/backends/zarr.py in open_group(cls, store, mode, synchronizer, group, consolidated, consolidate_on_close)
    256         if consolidated:
    257             # TODO: an option to pass the metadata_key keyword
--> 258             zarr_group = zarr.open_consolidated(store, **open_kwargs)
    259         else:
    260             zarr_group = zarr.open_group(store, **open_kwargs)

/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/convenience.py in open_consolidated(store, metadata_key, mode, **kwargs)
   1180 
   1181     # setup metadata sotre
-> 1182     meta_store = ConsolidatedMetadataStore(store, metadata_key=metadata_key)
   1183 
   1184     # pass through

/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/storage.py in __init__(self, store, metadata_key)
   2455             d = store[metadata_key].decode()  # pragma: no cover
   2456         else:  # pragma: no cover
-> 2457             d = store[metadata_key]
   2458         meta = json_loads(d)
   2459 

/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/mapping.py in __getitem__(self, key, default)
     78             if default is not None:
     79                 return default
---> 80             raise KeyError(key)
     81         return result
     82 

KeyError: 'pangeo-ecco-llc4320/grid/.zmetadata'

**Comment by rabernat** [comment]
@charlesbluca - can you weigh in on this? Is this related to #67? We really need your input to help resolve what is going on.

**Comment by rabernat** [comment]
Browsing the `pangeo-data` bucket (https://console.cloud.google.com/storage/browser/pangeo-data/), it appears that the LLC data has been removed from `pangeo-data` and moved to `pangeo-ecco-llc4320` (https://console.cloud.google.com/storage/browser/pangeo-ecco-llc4320). However, the intake catalog has not been updated, since #67 has not been merged.

So the best way to resolve this is to continue to work on #67.

**Comment by charlesbluca** [comment]
This issue is on me - on 1/6/20 I deleted out a majority of the data which had been copied from `gs://pangeo-data`, whose new locations can be found [here](https://docs.google.com/spreadsheets/d/1X0zaHX2y1Cn6ki1BaiTqytmZFIeo8ovirJeBLCE554s/edit?usp=sharing).

@rabernat is correct - moving forward on #67 will allow the intake catalogs to reflect this change.

**Comment by rabernat** [comment]
Ok, this should be fixed. Please try again on ocean.pangeo.io.

**Comment by hmkhatri** [comment]
Thanks.
It works now.
