### ISSUE TITLE
Cannot import data from fsspec or gcsfs

### ISSUE THREAD

**Issue by stb2145** [pangeo-data/pangeo-datastore#74]
* This is a similar issue to #73  - I've been importing ECCOv4r3 and SOSE datasets using `ds = xr.open_zarr(gcsfs.GCSFileSystem('pangeo-data/ecco/eccov4r3'), consolidated=True)` and `ds = xr.open_zarr(gcsfs.GCSMap('pangeo-data/SOSE'), consolidated=True)`, respectively. Yesterday when I tried to load the datasets I kept getting a similar `HTTPError: 404 Client Error: Not Found for url:` error as #73. 

* I realized from #67 that the datasets live elsewhere now; however, when I call them with the new file path with the gcsfs method - ` xr.open_zarr(gcsfs.GCSFileSystem('gcs://pangeo-ecco-eccov4r3/eccov4r3'))` and `xr.open_zarr(gcsfs.GCSFileSystem('gcs://pangeo-ecco-sose'))` - I now get an error that looks like 

**ERROR ECCO**:

> ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-658cc3647f75> in <module>
----> 1 ds = xr.open_zarr(gcsfs.GCSFileSystem('pangeo-ecco-eccov4r3/eccov4r3'))#, consolidated=True)
      2 ds

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/backends/zarr.py in open_zarr(store, group, synchronizer, chunks, decode_cf, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, consolidated, overwrite_encoded_chunks, **kwargs)
    594         synchronizer=synchronizer,
    595         group=group,
--> 596         consolidated=consolidated,
    597     )
    598     ds = maybe_decode_store(zarr_store)

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/backends/zarr.py in open_group(cls, store, mode, synchronizer, group, consolidated, consolidate_on_close)
    258             zarr_group = zarr.open_consolidated(store, **open_kwargs)
    259         else:
--> 260             zarr_group = zarr.open_group(store, **open_kwargs)
    261         return cls(zarr_group, consolidate_on_close)
    262 

/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/hierarchy.py in open_group(store, mode, cache_attrs, synchronizer, path, chunk_store)
   1111 
   1112     if mode in ['r', 'r+']:
-> 1113         if contains_array(store, path=path):
   1114             err_contains_array(path)
   1115         elif not contains_group(store, path=path):

/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/storage.py in contains_array(store, path)
     80     prefix = _path_to_prefix(path)
     81     key = prefix + array_meta_key
---> 82     return key in store
     83 
     84 

TypeError: argument of type 'GCSFileSystem' is not iterable

**ERROR SOSE**:

> _call non-retriable exception: Bucket is requester pays bucket but no user project provided.
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/gcsfs/core.py", line 507, in _call
    validate_response(r, path)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/gcsfs/core.py", line 179, in validate_response
    raise HttpError(error)
gcsfs.utils.HttpError: Bucket is requester pays bucket but no user project provided.
_call non-retriable exception: Bucket is requester pays bucket but no user project provided.
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/gcsfs/core.py", line 507, in _call
    validate_response(r, path)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/gcsfs/core.py", line 179, in validate_response
    raise HttpError(error)
gcsfs.utils.HttpError: Bucket is requester pays bucket but no user project provided.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-ab646d51bfee> in <module>
----> 1 ds = xr.open_zarr(gcsfs.GCSMap('gcs://pangeo-ecco-sose'))#, consolidated=True)
      2 ds

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/backends/zarr.py in open_zarr(store, group, synchronizer, chunks, decode_cf, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, consolidated, overwrite_encoded_chunks, **kwargs)
    594         synchronizer=synchronizer,
    595         group=group,
--> 596         consolidated=consolidated,
    597     )
    598     ds = maybe_decode_store(zarr_store)

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/backends/zarr.py in open_group(cls, store, mode, synchronizer, group, consolidated, consolidate_on_close)
    258             zarr_group = zarr.open_consolidated(store, **open_kwargs)
    259         else:
--> 260             zarr_group = zarr.open_group(store, **open_kwargs)
    261         return cls(zarr_group, consolidate_on_close)
    262 

/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/hierarchy.py in open_group(store, mode, cache_attrs, synchronizer, path, chunk_store)
   1114             err_contains_array(path)
   1115         elif not contains_group(store, path=path):
-> 1116             err_group_not_found(path)
   1117 
   1118     elif mode == 'w':

/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/errors.py in err_group_not_found(path)
     27 
     28 def err_group_not_found(path):
---> 29     raise ValueError('group not found at path %r' % path)
     30 
     31 

ValueError: group not found at path ''.

* I also try loading the datasets using `fsspec`: `ds = xr.open_zarr(fsspec.get_mapper('gcs://pangeo-ecco-eccov4r3/eccov4r33'))` and `ds = xr.open_zarr(fsspec.get_mapper('gcs://pangeo-ecco-sose'))`
And this is the error I get for both ECCO and SOSE.

**ERROR ECCO & SOSE**:

> _call non-retriable exception: Bucket is requester pays bucket but no user project provided.
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/gcsfs/core.py", line 507, in _call
    validate_response(r, path)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/gcsfs/core.py", line 179, in validate_response
    raise HttpError(error)
gcsfs.utils.HttpError: Bucket is requester pays bucket but no user project provided.
_call non-retriable exception: Bucket is requester pays bucket but no user project provided.
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/gcsfs/core.py", line 507, in _call
    validate_response(r, path)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/gcsfs/core.py", line 179, in validate_response
    raise HttpError(error)
gcsfs.utils.HttpError: Bucket is requester pays bucket but no user project provided.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-6a04e8b1bfc1> in <module>
----> 1 ds = xr.open_zarr(fsspec.get_mapper('gcs://pangeo-ecco-eccov4r3/eccov4r33'))
      2 ds

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/backends/zarr.py in open_zarr(store, group, synchronizer, chunks, decode_cf, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, consolidated, overwrite_encoded_chunks, **kwargs)
    594         synchronizer=synchronizer,
    595         group=group,
--> 596         consolidated=consolidated,
    597     )
    598     ds = maybe_decode_store(zarr_store)

/srv/conda/envs/notebook/lib/python3.7/site-packages/xarray/backends/zarr.py in open_group(cls, store, mode, synchronizer, group, consolidated, consolidate_on_close)
    258             zarr_group = zarr.open_consolidated(store, **open_kwargs)
    259         else:
--> 260             zarr_group = zarr.open_group(store, **open_kwargs)
    261         return cls(zarr_group, consolidate_on_close)
    262 

/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/hierarchy.py in open_group(store, mode, cache_attrs, synchronizer, path, chunk_store)
   1114             err_contains_array(path)
   1115         elif not contains_group(store, path=path):
-> 1116             err_group_not_found(path)
   1117 
   1118     elif mode == 'w':

/srv/conda/envs/notebook/lib/python3.7/site-packages/zarr/errors.py in err_group_not_found(path)
     27 
     28 def err_group_not_found(path):
---> 29     raise ValueError('group not found at path %r' % path)
     30 
     31 

ValueError: group not found at path ''

**Comment by TomAugspurger** [comment]
I think

>  gcsfs.utils.HttpError: Bucket is requester pays bucket but no user project provided.

points at the error. Basically, the requests made to this dataset need to be associated with some google project that'll be billed for the egress charges. https://gcsfs.readthedocs.io/en/latest/#credentials talks about this a bit.

Where are you accessing the data from? This this on a pangeo binder or jupyterhub?

**Comment by TomAugspurger** [comment]
@stb2145 this seems to work as long as you have a working token / project for google cloud.

```python
In [22]: ds = xr.open_zarr(mapping, consolidated=True)

In [23]: fs = gcsfs.GCSFileSystem(requester_pays=True)

In [24]: mapping = fs.get_mapper('pangeo-ecco-sose')

In [25]: ds = xr.open_zarr(mapping, consolidated=True)

In [26]: ds
Out[26]:
<xarray.Dataset>
Dimensions:   (XC: 2160, XG: 2160, YC: 320, YG: 320, Z: 42, Zl: 42, Zp1: 43, Zu: 42, time: 438)
Coordinates:
    Depth     (YC, XC) float32 dask.array<chunksize=(320, 2160), meta=np.ndarray>
    PHrefC    (Z) float32 dask.array<chunksize=(42,), meta=np.ndarray>
```

I'll hopefully figure out how to make this work transparently inside our jupyterhub / binder tomorrow.

**Comment by stb2145** [comment]
Thank you @TomAugspurger for your help, and @rabernat for the fix on ocean.pangeo.io. Everything is in working order now!
