### ISSUE TITLE
FileNotFoundError when intake.Catalog(url)

### ISSUE THREAD

**Issue by statiksof** [pangeo-data/pangeo-datastore#78]
Hi, just trying to test ```intake-esm``` by following the setps from the README (https://github.com/pangeo-data/pangeo-datastore)

```
import intake
cat_url = 'https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/master.yaml'
cat = intake.Catalog(cat_url)

```
```
print(intake__version__)
0.5.3
```
, but I got this error:

```
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-14-8a015e3096ac> in <module>
----> 1 cat = intake.Catalog(cat_url)

/python3.6/site-packages/intake/__init__.py in open_catalog(uri, **kwargs)
    151         raise ValueError('Unknown catalog driver (%s), supply one of: %s'
    152                          % (driver, list(sorted(registry))))
--> 153     return registry[driver](uri, **kwargs)
    154 
    155 

/python3.6/site-packages/intake/catalog/local.py in __init__(self, path, autoreload, **kwargs)
    563         self.autoreload = autoreload  # set this to False if don't want reloads
    564         self.filesystem = kwargs.pop('fs', None)
--> 565         super(YAMLFileCatalog, self).__init__(**kwargs)
    566 
    567     def _load(self, reload=False):

/python3.6/site-packages/intake/catalog/base.py in __init__(self, name, description, metadata, auth, ttl, getenv, getshell, persist_mode, storage_options, *args)
    111         self.updated = time.time()
    112         self._entries = self._make_entries_container()
--> 113         self.force_reload()
    114 
    115     @classmethod

/python3.6/site-packages/intake/catalog/base.py in force_reload(self)
    170     def force_reload(self):
    171         """Imperative reload data now"""
--> 172         self._load()
    173         self.updated = time.time()
    174 

/python3.6/site-packages/intake/catalog/local.py in _load(self, reload)
    588             self._dir = get_dir(self.path)
    589 
--> 590             with file_open as f:
    591                 text = f.read().decode()
    592             if "!template " in text:

~/.local/lib/python3.6/site-packages/fsspec/core.py in __enter__(self)
     96         mode = self.mode.replace("t", "").replace("b", "") + "b"
     97 
---> 98         f = self.fs.open(self.path, mode=mode)
     99 
    100         self.fobjects = [f]

~/.local/lib/python3.6/site-packages/fsspec/spec.py in open(self, path, mode, block_size, cache_options, **kwargs)
    723                 autocommit=ac,
    724                 cache_options=cache_options,
--> 725                 **kwargs
    726             )
    727             if not ac:

~/.local/lib/python3.6/site-packages/fsspec/implementations/http.py in _open(self, url, mode, block_size, cache_options, **kwargs)
    148         if block_size:
    149             return HTTPFile(
--> 150                 self, url, self.session, block_size, cache_options=cache_options, **kw
    151             )
    152         else:

~/.local/lib/python3.6/site-packages/fsspec/implementations/http.py in __init__(self, fs, url, session, block_size, mode, cache_type, cache_options, size, **kwargs)
    236             cache_type=cache_type,
    237             cache_options=cache_options,
--> 238             **kwargs
    239         )
    240         self.cache.size = self.size or self.blocksize

~/.local/lib/python3.6/site-packages/fsspec/spec.py in __init__(self, fs, path, mode, block_size, autocommit, cache_type, cache_options, **kwargs)
    955         if mode == "rb":
    956             if not hasattr(self, "details"):
--> 957                 self.details = fs.info(path)
    958             self.size = self.details["size"]
    959             self.cache = caches[cache_type](

~/.local/lib/python3.6/site-packages/fsspec/implementations/http.py in info(self, url, **kwargs)
    182             # get failed, so conclude URL does not exist
    183             if size is False:
--> 184                 raise FileNotFoundError(url)
    185         return {"name": url, "size": size or None, "type": "file"}
    186 

FileNotFoundError: https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/master.yaml
```

**Comment by rabernat** [comment]
Just for completeness, could you update your issue with the *exact code* you entered to raise this error.

I am not able to reproduce.

Please also report your intake version.
```python
import intake
print(intake.__version__)
```

**Comment by rabernat** [comment]
Very strange. I have the exact same version of intake and cannot reproduce this. Pinging @martindurant, the intake ninja.

**Comment by martindurant** [comment]
Also your version of fsspec, please

**Comment by statiksof** [comment]
@martindurant 0.6.0

**Comment by martindurant** [comment]
I recommend trying with the latest fsspec version or perhaps even master

**Comment by rabernat** [comment]
I have fsspec 0.6.2 and it works fine for me.

**Comment by statiksof** [comment]
@rabernat @martindurant I have now upgraded ```fsspec``` to ```0.6.2```. Just for information, fsspec was installed with ```pip```, but now all packages are installed with ```conda```. 
This the error I have now (``` cat.atmosphere.gmet_v1.to_dask()```):
```
Traceback (most recent call last):
  File "/python3.6/site-packages/fsspec/mapping.py", line 76, in __getitem__
    result = self.fs.cat(key)
  File "</python3.6/site-packages/decorator.py:decorator-gen-13>", line 2, in cat
  File "/python3.6/site-packages/gcsfs/core.py", line 50, in _tracemethod
    return f(self, *args, **kwargs)
  File "/python3.6/site-packages/gcsfs/core.py", line 845, in cat
    r.raise_for_status()
  File "/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.googleapis.com/download/storage/v1/b/pangeo-ncar-gmet/o/.zmetadata?alt=media

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/python3.6/site-packages/intake_xarray/base.py", line 69, in to_dask
    return self.read_chunked()
  File "/python3.6/site-packages/intake_xarray/base.py", line 44, in read_chunked
    self._load_metadata()
  File "/python3.6/site-packages/intake/source/base.py", line 117, in _load_metadata
    self._schema = self._get_schema()
  File "/python3.6/site-packages/intake_xarray/base.py", line 18, in _get_schema
    self._open_dataset()
  File "/python3.6/site-packages/intake_xarray/xzarr.py", line 31, in _open_dataset
    self._ds = xr.open_zarr(self._mapper, **self.kwargs)
  File "/python3.6/site-packages/xarray/backends/zarr.py", line 596, in open_zarr
    consolidated=consolidated,
  File "/python3.6/site-packages/xarray/backends/zarr.py", line 258, in open_group
    zarr_group = zarr.open_consolidated(store, **open_kwargs)
  File "/python3.6/site-packages/zarr/convenience.py", line 1182, in open_consolidated
    meta_store = ConsolidatedMetadataStore(store, metadata_key=metadata_key)
  File "/python3.6/site-packages/zarr/storage.py", line 2457, in __init__
    d = store[metadata_key]
  File "/python3.6/site-packages/fsspec/mapping.py", line 80, in __getitem__
    raise KeyError(key)
KeyError: 'pangeo-ncar-gmet/.zmetadata'

```

**Comment by agoodm** [comment]
I can confirm I am getting the same error as that shown above (intake 0.5.4, fsspec 0.6.2). I have gotten it for all datasets I have tried in the catalogue where `consolidated: True`. The exact error message in the request is:
```
$ curl https://www.googleapis.com/storage/v1/b/pangeo-ncar-gmet/o/
{
  "error": {
    "code": 400,
    "message": "Bucket is requester pays bucket but no user project provided.",
    "errors": [
      {
        "message": "Bucket is requester pays bucket but no user project provided.",
        "domain": "global",
        "reason": "required"
      }
    ]
  }
}
```

For the other zarr datasets in the catalogue I also get this error:
```python
In [19]: cat.atmosphere.gpcp_cdr_daily_v1_3.to_dask()                                                                                            
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-e47249abf02b> in <module>
----> 1 cat.atmosphere.gpcp_cdr_daily_v1_3.to_dask()

~/opt/lib/python3.7/site-packages/intake_xarray/base.py in to_dask(self)
     67     def to_dask(self):
     68         """Return xarray object where variables are dask arrays"""
---> 69         return self.read_chunked()
     70 
     71     def close(self):

~/opt/lib/python3.7/site-packages/intake_xarray/base.py in read_chunked(self)
     42     def read_chunked(self):
     43         """Return xarray object (which will have chunks)"""
---> 44         self._load_metadata()
     45         return self._ds
     46 

~/opt/lib/python3.7/site-packages/intake/source/base.py in _load_metadata(self)
    115         """load metadata only if needed"""
    116         if self._schema is None:
--> 117             self._schema = self._get_schema()
    118             self.datashape = self._schema.datashape
    119             self.dtype = self._schema.dtype

~/opt/lib/python3.7/site-packages/intake_xarray/base.py in _get_schema(self)
     16 
     17         if self._ds is None:
---> 18             self._open_dataset()
     19 
     20             metadata = {

~/opt/lib/python3.7/site-packages/intake_xarray/xzarr.py in _open_dataset(self)
     29 
     30         self._mapper = get_mapper(self.urlpath, **self.storage_options)
---> 31         self._ds = xr.open_zarr(self._mapper, **self.kwargs)
     32 
     33     def close(self):

~/opt/lib/python3.7/site-packages/xarray/backends/zarr.py in open_zarr(store, group, synchronizer, chunks, decode_cf, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, consolidated, overwrite_encoded_chunks, **kwargs)
    594         synchronizer=synchronizer,
    595         group=group,
--> 596         consolidated=consolidated,
    597     )
    598     ds = maybe_decode_store(zarr_store)

~/opt/lib/python3.7/site-packages/xarray/backends/zarr.py in open_group(cls, store, mode, synchronizer, group, consolidated, consolidate_on_close)
    258             zarr_group = zarr.open_consolidated(store, **open_kwargs)
    259         else:
--> 260             zarr_group = zarr.open_group(store, **open_kwargs)
    261         return cls(zarr_group, consolidate_on_close)
    262 

~/opt/lib/python3.7/site-packages/zarr/hierarchy.py in open_group(store, mode, cache_attrs, synchronizer, path, chunk_store)
   1144             err_contains_array(path)
   1145         elif not contains_group(store, path=path):
-> 1146             err_group_not_found(path)
   1147 
   1148     elif mode == 'w':

~/opt/lib/python3.7/site-packages/zarr/errors.py in err_group_not_found(path)
     23 
     24 def err_group_not_found(path):
---> 25     raise ValueError('group not found at path %r' % path)
     26 
     27 

ValueError: group not found at path ''
```

**Comment by martindurant** [comment]
Ah, so the real error message is there: you must provide the project under which you will be billed (which *might* have been auto-detected at instantiation) and also `requester_pays=True`, saying that for this particular usage of gcsfs, you accept the charges. From the particular form of the error message, I would assume it's the former which is missing.

**Comment by agoodm** [comment]
I see, that makes sense. This also means that authentication is now required to access theses datasets from outside pangeo. On `ocean.pangeo.io`, I can indeed access them just fine. 

@rabernat Is there a way to get access now from outside pangeo?

Thanks!

**Comment by rabernat** [comment]
> I'm new to using Google Cloud (we mainly use AWS S3 over here) but it looks like we need access to the pangeo Google Cloud project to do this. I think this should be clarified somewhere, since the intake-esm catalogues can be accessed anywhere for free right now without authentication, so I initially assumed that would be the case for these catalogues as well.

Thanks @agoodm for raising this issue and helping us get to the bottom of things. We are in new territory here. As a bit of background, the shift to requester pays was motivated by several large (~$1000 per day) egress charges we got with public datasets, which really screwed up our cloud budget. Pangeo in its current form is not sustainable if we have to absorb arbitrarily large egress charges at random.

You don't necessary need credentials from Pangeo's google cloud project to access the google cloud datasets. You just need to credentials linked to *any* google cloud billing account, to charge the egress fees. If you are reading the data from the same cloud region (`us-central`) there are no egress fees, but you still need the credentials for requester pays to work.

Where are you trying to read the data from? If it is from outside of `us-central` is will cost money, and you need to pay that cost yourself, by creating your own google cloud project and using its credentials when accessing the datasets.

Does this make sense?

**Comment by statiksof** [comment]
@rabernat @agoodm just an understanding question. Is it really the same error as the one I mentioned above? I mean in my case:
```
KeyError: 'pangeo-ncar-gmet/.zmetadata'
```

Is there any other minimal code to test the installation of ```intake-esm``` without region/billing issues?

**Comment by rabernat** [comment]
intake-esm only applies to datasets that are stored using [esm collection spec](https://github.com/NCAR/esm-collection-spec). AFAIK, none of these is stored in requester pays buckets.

You can see an example here:
http://catalog.pangeo.io/climate/cmip6_gcs

**Comment by agoodm** [comment]
@rabernat Thanks for clarifying! I was initially unsure if access from outside the pangeo project account was possible since I still kept getting bad request errors using my default credentials. However, I was able to get it to work when using service account credentials. For reference in case others run into this problem, here are the exact steps I took:
1) Set up a google cloud account if you do not already have one and create a project.
https://cloud.google.com/tpu/docs/setup-gcp-account
2) Install the google cloud SDK
```
 conda install -c conda-forge google-cloud-sdk 
```
3) Initialize the SDK CLI. This will let you set your default project name.
```
gcloud auth login
gcloud init
```
4) Add a service account.
https://developers.google.com/android/management/service-account
Important: **Make sure it has the Service Usage Admin role.** When finished, create and download an account key.
5) Set the default authentication credentials to the key file you just created:
```
export GOOGLE_APPLICATION_CREDENTIALS=/path/to/key.json
```
After this you should be able to run the intake examples as you would on a pangeo deployment!=.

@statiksof Yes I was getting the same error as you until I took these steps, or if running from a pangeo deployment (eg, https://binder.pangeo.io/). Try this out and see if it works for you.

**Comment by jacobtomlinson** [comment]
The instructions for accessing a requester pays bucket were really useful. This info should be elevated to the README.

**Comment by rabernat** [comment]
@charlesbluca - could you add @agoodm's explanations to the README of this repo and to catalog.pangeo.io?

**Comment by charlesbluca** [comment]
I agree - this information should be more publicly available. I'm currently in the process of adding it to the README and website templates for relevant requester pays data.

I think there should be an easier way to generate an authentication credentials token, rather than making a service account and downloading its key file:

```
gcloud auth application-default login
``` 

This may require some permissions given to the user in question (which should be the owner of their own project), but may be simpler than the service account method. Could someone who has tried the workaround and has their own project confirm this?

For the time being, these instructions are perfect - thank you @agoodm!

**Comment by jacobtomlinson** [comment]
Something simpler than a service account would be good. For example I'm not allowed to make service accounts in my org.

**Comment by martindurant** [comment]
Would it be reasonable for the mapper implementation to take an optional arguments specifying which exceptions should be treated as not-found?
