### ISSUE TITLE
How to add data error-reporting link to catalog?

### ISSUE THREAD

**Issue by naomi-henderson** [pangeo-data/pangeo-datastore#79]
@charlesbluca , I think we need more information in the Pangeo Catalog pages which make it clear how to report problems or raise issues with the datasets.  

For example, for the GCS CMIP6 collection, 
we could include this information in `https://storage.googleapis.com/cmip6/pangeo-cmip6.json`. I think information from this json file is what shows up on the Pangeo Catalog Page in the `Metadata` section, no?  So we could add a new keyword, possible 'feedback_url', between `description` and `catalog_file` which looks something like:

feedback_url: "Report issues with the GCS CMIP6 datasets at https://docs.google.com/forms/d/e/1FAIpQLSeISi54dqekkknPp8IrBr-uioM2TGGiW7xGpW6Q_9-9WFlWTQ/viewform.  Request additional data at https://docs.google.com/forms/d/e/1FAIpQLScFjA5IddqBs2Rc0xGbzn32NPq12TKr-b-8KGtXWyNDK5sJCg/viewform",

Alternatively I could add this information to the description, but it might get lost there.

**Comment by naomi-henderson** [comment]
I have changed the json file, hopefully this does not cause issues downstream ...

**Comment by rabernat** [comment]
This is a great idea @naomi-henderson!

Just for discussion, would it make sense to use github issues to track certain types of errors?

**Comment by naomi-henderson** [comment]
Yes @rabernat - there are some snarly issues with the data which do require community involvement!  Currently we raise this these data issues many different places (slack, various github repositories, etc) - it makes sense to identify a single repository for this. Do you have a preference?  

I will also add that link to the metadata - it seems to me that the Pangeo Catalog with the listing is the right place to post it.

**Comment by rabernat** [comment]
I agree that there are too many channels, and we need to think about a way to streamline. The advantage of using github is that we can link problems to solutions. I'll brainstorm on this.

Regarding adding fields to the ESM Collection json file, the place to discuss that would be https://github.com/NCAR/esm-collection-spec/. That's where the spec is formally defined. As far as I know, it's no problem to simply add additional fields, as long as the required ones are still present. However, if we are defining a new convention that we want to use across all our catalogs, we should probably add it to the spec somehow.

**Comment by charlesbluca** [comment]
A simple solution that comes to mind that might not conflict with current ESMCol specifications would be to include a link on the catalog website to report an issue regarding any dataset - that might make it easier to specify this repo (or any repo for that matter) as a place to report those types of issues.
