### ISSUE TITLE
post your workflows for producing Zarr datasets here!

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-datastore#8]
Lots of folks are trying to produce Zarr datasets from existing netCDF archives.

Let's use this issue to share what people are actually doing. I think everyone is looking for more examples.

I'll start with some of my own examples:
- Convert CM2.6 MOM5 Ocean Model netCDF to Zarr: https://gist.github.com/rabernat/4ae286464f55a75e30b55f529195aff0

I think @charlesbluca and @ktyle may have some examples to share as well. Post em up!

**Comment by charlesbluca** [comment]
It's a work in progress, but here is my repo

https://github.com/charlesbluca/tracmip-zarr

Trying to be as descriptive as possible with the process of getting my environment running, in case we want to get beginners into the process. Feel free to comment with issues in what I have so far!

**Comment by rabernat** [comment]
Maybe @nbren12 can post how he created his recently uploaded zarr dataset?

**Comment by nbren12** [comment]
Sure. Here's my workflow:https://nbviewer.jupyter.org/gist/nbren12/fe8e1f84c488bb862227abcc2a2c2186

I couldn't get `open_mfdataset` to work, and I was nervous about losing my work, so I wrote the fields directly using zarr. I used `dask.bag` and `distributed` for parallelism.

**Comment by jhamman** [comment]
The GMET dataset that I posted a long time ago was built using this simple xarray/dask workflow: https://gist.github.com/jhamman/f25a6d016d884cb23098ba70c870bc09

**Comment by rafa-guedes** [comment]
Sharing here some code I recently used to convert ERA5 10-m wind components netcdf monthly files into zarr:
https://gist.github.com/rafa-guedes/3f28ab0a2777fb3327d16d1f0b4e56eb

**Comment by NickMortimer** [comment]
Hey I just got round to publishing some stuff on Argo to Zarr
https://medium.com/@nicolasmortimer/argo-floats-zarr-and-pangeo-d74fc6d4ce35

https://github.com/NickMortimer/argo_to_zarr
