### ISSUE TITLE
Adding data for national-scale ML streamflow prediction

### ISSUE THREAD

**Issue by jsadler2** [pangeo-data/pangeo-datastore#80]
I have some Zarr datasets in Pangeo AWS S3 buckets that we can add to the catalogue. These datasets were originally intended for national-scale streamflow prediction using machine learning. The datasets are in three buckets:
* `arn:aws:s3:::pangeo-nhd-catchment-attributes`
* `arn:aws:s3:::pangeo-nldas-hru-forcing`
* `arn:aws:s3:::pangeo-usgs-flow-observations`

**Comment by jsadler2** [comment]
To do that, do I add these to one of the `yaml` files in the `intake-catalogs` directory and submit a PR? If that's the case, I would assume it fits best into [intake-catalogs/hydro.yaml](https://github.com/pangeo-data/pangeo-datastore/blob/master/intake-catalogs/hydro.yaml)?

**Comment by jhamman** [comment]
@jsadler2 - you've got it. #62 is performing a similar task and may be a decent starting template for you.
