### ISSUE TITLE
Consolidating/relocating GFDL_CM2.6 datasets

### ISSUE THREAD

**Issue by charlesbluca** [pangeo-data/pangeo-datastore#87]
Talking to @rabernat, it seemed like there was a desire to transition the GFDL CM2.6 data in our catalogs to an intake-esm entry (instead of the Intake catalog it currently resides in), and eventually moving the data itself to Google's own CMIP6 bucket.

I'm happy to make the ESM collection and do the data migration, but I am a little unfamiliar with the format of these datasets and would appreciate any insights on how to go about doing this.

cc @raphaeldussin @jhamman

**Comment by rabernat** [comment]
So you will have to define an esmcollection for CM2.6. You'll have to think about what fields you have in your CSV. I would try to copy CMIP6 as much as possible. Perhaps you will want `institution_id`, `source_id`, `experiment_id`, and `variables`. Where `variables`, would match the prefix on https://catalog.pangeo.io/climate/cmip6_gcs, i.e. `ocean`, `ocean_surface`, etc.

**Comment by charlesbluca** [comment]
CM 2.6 has been copied, with an ESM collection created for it. The next course of action is to clear out `gs://pangeo-gfdl-cm26` in a way that doesn't impact users - do we know in particular who was using this data?

**Comment by charlesbluca** [comment]
Finished this off by deleting the existing bucket `gs://pangeo-gfdl-cm26` and its contents - seemed like there wasn't much interaction going on with the datasets that wasn't handled by the catalog redirection.

The datasets now reside at `gs://cmip6/GFDL_CM2_6`.

**Comment by rabernat** [comment]
Fantastic Charles! Thanks so much for seeing this through!
