### ISSUE TITLE
Cleaning out the pangeo-data bucket by moving all meom simulation into pangeo-meom bucket

### ISSUE THREAD

**Issue by auraoupa** [pangeo-data/pangeo-datastore#88]
Hi @rabernat and @charlesbluca. I was interrupted in my attempt of cleaning the pangeo-data last year (https://discourse.pangeo.io/t/cleaning-out-the-pangeo-data-google-cloud-storage-bucket/353/27) and I'm sorry that I did not go back to it sooner, I'm fully commited now to end it now!

When I left off I had some issues accessing the newly created pangeo-meom bucket, for instance when I do a `gsutil -u pangeo-181919 ls -a gs://pangeo-meom` I get `AccessDeniedException: 403 auraoupa@gmail.com does not have serviceusage.services.use access to project 464800473488`. Same on the console, when I try to upload a file I get a `Bucket is requester pays bucket but no user project provided.` even if it says that the bucket is linked to the pangeo project. Is it possible that the permissions for this bucket are not opened enough for me to put data there ?

Also I prepared the future addition to the catalog by writing a yaml block to put in ocean.yaml (https://github.com/auraoupa/pangeo-data-catalog/blob/master/ocean.yaml) and a yaml file MEOM-NEMO.yaml (https://github.com/auraoupa/pangeo-data-catalog/blob/master/MEOM-NEMO.yaml) for when the data are transfered from pangeo-data to pangeo-meom.

Thanks in advance for your help !

**Comment by charlesbluca** [comment]
Sorry for the delay! I've given your account associated with the project `serviceusage.services.use` access to the project - hopefully this should fix the issue!

**Comment by charlesbluca** [comment]
Were you able to get this transfer working @auraoupa? Is there any way I can help further?

**Comment by auraoupa** [comment]
Hi @charlesbluca, thanks for your message !
I think I managed to put everything I wanted on the pangeo-meom bucket but when wanting to test accessing it from ocean.pangeo.io I could not find what I just uploaded ...
For instance the repo eNATL60-BLBT02-SSU-1h is on both bucket, the command 
`ds = xr.open_zarr(gcsfs.GCSMap('pangeo-data/eNATL60-BLB002-SSU-1h'))` works fine but  
`ds = xr.open_zarr(gcsfs.GCSMap('pangeo-meom/eNATL60-BLBT02-SSU-1h'))` gets `ValueError: group not found at path ''` (I also tried with `fs = gcsfs.GCSFileSystem(project='pangeo-181919', token='anon', access='read_only')` ...)
The only difference between the 2 I could find is the Storage Class : it is set to Regional for pangeo-data and Standart for pangeo-meom, can it be the problem here ? Is it possible to change it ?
When I am sure I can access the data from ocean.pangeo.io, I will clean up my data from the pangeo-data.

**Comment by charlesbluca** [comment]
Just checked out the bucket and I was able to access all the zarr stores - were you able to resolve the issue?

For reference, here is a code snippet I used to check the data:

```
import xarray as xr
import gcsfs

fs = gcsfs.GCSFileSystem('pangeo-181919', requester_pays=True)

dsets = {}

for path in fs.ls('pangeo-meom'):
    try:
        zmap = fs.get_mapper(path)
        ds = xr.open_zarr(zmap)
        dsets[path] = ds
        print(path)
    except ValueError:
        print(f'failure to open {path}')
```

**Comment by auraoupa** [comment]
Your syntax is working fine for me too, it looks like the keyword 'requester_pays=True' is important and must replace 'token='anon' in my scripts. Thanks !

**Comment by charlesbluca** [comment]
Glad I was able to help! In your MEOM-NEMO catalog, it looks like there are [some](https://github.com/auraoupa/pangeo-data-catalog/blob/94ff4e6bd5e490941ecee68ed18d1184227087e6/MEOM-NEMO.yaml#L7) [grids](https://github.com/auraoupa/pangeo-data-catalog/blob/94ff4e6bd5e490941ecee68ed18d1184227087e6/MEOM-NEMO.yaml#L64) that point to empty directories in `gs://pangeo-meom` - are there any other datasets that could still be relocated?

If not, I'm happy to get a PR going so we can add this data to the catalog!

**Comment by auraoupa** [comment]
Yes there were some datasets yet to upload to pangeo-meom, it is done now !
I updated the piece of catalog : https://github.com/auraoupa/pangeo-data-catalog/blob/master/MEOM-NEMO.yaml, so I think we can have a PR going now ?
Also I cleaned up the pangeo-data from all the (e)NATL60 data, I hope I didn't forget anything ...

**Comment by charlesbluca** [comment]
Thanks for all your help in moving the data and making the catalog! I opened up a PR at #105 - there's still some work to be done with consolidating the metadata of the datasets, but once that is done we should be able to merge.

**Comment by auraoupa** [comment]
Thanks to you !

**Comment by charlesbluca** [comment]
Merged the pull request - the data can be viewed at:

https://catalog.pangeo.io/browse/master/ocean/MEOM_NEMO/
