### ISSUE TITLE
Moving soil grids and camels data to requester pays buckets

### ISSUE THREAD

**Issue by charlesbluca** [pangeo-data/pangeo-datastore#95]
Just noticed that there are several datasets in `hydro.yaml` and `camels.yaml` that are located in `gs://pangeo-data`; is this being done to get around some form of authentication issues?

If not, is it okay to move this data to a preexisting/new bucket with requester pays? I was thinking `gs://pangeo-camels` to correspond with the current AWS bucket.

cc @jhamman

**Comment by jhamman** [comment]
@charlesbluca - its okay if you move these. Let me know if you need help making it happen.

**Comment by charlesbluca** [comment]
Thanks for the go ahead! Is there an institution assigned to camels and soil grids that I could include in the bucket name?

**Comment by jhamman** [comment]
NCAR for both. Thanks!

**Comment by charlesbluca** [comment]
Copied the data to requester pays buckets and made a PR #98 to reflect the changes in the catalog - once it's merged we can remove the old copies of the data.

**Comment by charlesbluca** [comment]
Closing this now that the data is moved and the catalog updated.
